### ISSUE TITLE
api error 

### ISSUE THREAD

**Issue by anoureldin** [ytrevor81/TradingView-Binance-Telegram-Bot#4]
Thanks for fast reply 
it's working now and bot start but when i try to get balance or history i get 
![image](https://user-images.githubusercontent.com/11461698/113465517-44049900-943d-11eb-8e3a-7cec95efa0d3.png)

then i changed 
        self.client.API_URL = 'https://testnet.binance.vision/api' #only for testing
to 

        self.client.API_URL = 'https://api1.binance.com' #only for testing
then i get 

![image](https://user-images.githubusercontent.com/11461698/113465529-5f6fa400-943d-11eb-93bc-2befdc419604.png)

**Comment by ytrevor81** [comment]
It looks like you're getting a BinanceAPI error raised by the python-binance library. Is your API key and secret key set up properly on Binance, Spot Test, and _config.py_?

There are 2 methods that worked for me in avoiding the BinanceAPI error: 

1. `client.API_URL = 'https://testnet.binance.vision/api'` On my end it works fine. Is your Spot Test API key and secret key set up?
2. `#client.API_URL = 'https://testnet.binance.vision/api'` and `client = Client(config.BINANCE_MAIN_API_KEY, config.BINANCE_MAIN_SECRET_KEY)` 
Commenting out the API_URL entirely and replacing the spot test keys in the Client object with my main binance api keys worked in connecting to the main Binance API (just add your main binance keys in _config.py_). python-binance has a default API_URL variable that uses the correct link for the main Binance API.
